name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up Node.js

        uses: actions/setup-node@v2

        with:
          node-version: 14

      - name: Install dependencies

        run: npm ci

      - name: Run tests

        run: npm test

  release:
    runs-on: ubuntu-latest

    needs: test

    if: success()

    steps:
      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up Node.js

        uses: actions/setup-node@v2

        with:
          node-version: 14

      - name: Install dependencies

        run: npm ci

      - name: Create release

        uses: actions/create-release@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.VERSION }}

          release_name: Release v${{ env.VERSION }}

          body_path: changelog.md

      - name: Publish to npm

        run: npm publish

        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
